# Generated by Django 3.0 on 2020-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200622_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ManyToManyField(to='account.Batch'),
        ),
    ]
