# Generated by Django 3.1 on 2020-08-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200809_1327'),
        ('account', '0005_auto_20200727_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfomance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
