# Generated by Django 3.1 on 2020-09-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200809_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomance',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='Perfomance',
        ),
    ]
