# Generated by Django 3.0 on 2020-06-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200622_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='optioon',
            new_name='option',
        ),
    ]
