# Generated by Django 3.0 on 2020-06-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200622_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='iscoorect',
            new_name='iscorrect',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='ques',
            new_name='question',
        ),
    ]
