# Generated by Django 3.1 on 2020-09-06 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_option_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to=settings.AUTH_USER_MODEL),
        ),
    ]
