# Generated by Django 3.1 on 2020-09-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='end_time',
            new_name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='option',
            name='select',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='full_marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='no_of_ques',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='student',
        ),
    ]
