# Generated by Django 3.1 on 2020-09-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200907_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['time_stamp'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
