# Generated by Django 3.1 on 2020-09-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_quiztaker_usersanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='qno',
        ),
    ]
