# Generated by Django 3.1 on 2020-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_questions_qno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
