# Generated by Django 3.1 on 2020-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20200907_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
