# Generated by Django 3.1 on 2020-09-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quiz_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='questions',
            new_name='question',
        ),
    ]
