# Generated by Django 3.1 on 2020-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20200907_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='usersanswer',
            old_name='option',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='roll_out',
            field=models.BooleanField(default=False),
        ),
    ]
